---
.travis.yml:
  secure: "RrAmWtM6eTjZZzD954AIgR179Pqp14lzHhd/C9cpKbTPynLncuim08CEvjmq+7pgAy9XDg1d02x3udfZt4btR1sBdyNRpNN3yUhWptmGU61HRJdiZq+nSLQkIYsqXanhk+O3NndFojO58WRD01dkWEc6HRHjlivuYNxDXmMkg9k="
#spec/spec_helper_acceptance.rb:
# Temporarily unmanage spec_helper_acceptance (iss. #133)
#  windows: true
#  dependencies:
#    - puppetlabs-stdlib
spec/acceptance/nodesets/docker/centos-5.yml:
  unmanaged: true
spec/acceptance/nodesets/docker/centos-6.yml:
  unmanaged: true
spec/acceptance/nodesets/docker/centos-7.yml:
  unmanaged: true
spec/acceptance/nodesets/docker/debian-7.yml:
  unmanaged: true
spec/acceptance/nodesets/docker/debian-8.yml:
  unmanaged: true
spec/acceptance/nodesets/docker/ubuntu-12.04.yml:
  unmanaged: true
spec/acceptance/nodesets/docker/ubuntu-14.04.yml:
  unmanaged: true
spec/acceptance/nodesets/docker/ubuntu-16.04.yml:
  unmanaged: true
spec/acceptance/nodesets/centos-511-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/centos-66-x64-pe.yml:
  unmanaged: true
spec/acceptance/nodesets/centos-66-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/centos-72-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/debian-78-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/debian-82-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/ubuntu-server-1204-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/ubuntu-server-1404-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/ubuntu-server-1604-x64.yml:
  unmanaged: true
